### ISSUE TITLE
Settings v2 feedback

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#1000]
This issue is for any questions/comments/feedback related to the new settings page.

Changes:
* [x] Update the layout of the dictionaries popup; the UI is more compressed now, and the popup is no longer full-height. (#1146)
* [x] Add icons to the section headers. (#1148)
* [x] Make the popup preview persistent and not require a toggle/option. (#1151)
* [x] Add an expand/collapse option to popups to allow their size to be changed by the user if desired. (#1149)
* [x] Make it more clear that the buttons with the ">" icon on the right are used to open a popup. (#1155)
* [x] Remove "Top" link. (#1169)

**Comment by Thermospore** [comment]
Just built a new PC and am setting up yomichan again; importing settings doesn't seem to do anything. File select pops up but nothing happens after selection. Not sure if I'm doing something wrong or maybe the importer broke with a recent change? Here is my export: 
[yomichan-settings-2020-11-10-01-13-55.zip](https://github.com/FooSoft/yomichan/files/5516816/yomichan-settings-2020-11-10-01-13-55.zip)

I was on win 8.1 before and now I'm on 10, if that matters

Very much appreciated!
-Tyler

**Comment by toasted-nutbread** [comment]
There was a bug in the previous release which caused settings imports to not always work correctly. If you open up the JSON file and add the line `"fieldTemplates": null,` to the `"anki": {...}` block, that should allow it to be imported.

**Comment by toasted-nutbread** [comment]
Quoting feedback from @FooSoft https://github.com/FooSoft/yomichan/issues/1079#issuecomment-739554939:

> * The "Show popup preview"  toggle jumps to top of the screen when enabled and returns to screen center when disabled. Not sure if it's supposed to do this or if it is a bug (I am getting this on Chromium). When expanded, there is also a lot of vertical white space inserted between the elements. We should probably have the preview contents be right below the toggle and not have the toggle jump around depending on its state. Also, would there ever be a time where the user would not want to display the preview at all?

The reason it jumps is because the `<iframe>` of the preview isn't visible until it's enabled, causing a layout change. I tested an animation on the frame to prevent the immediate jump (but still moved to top), but there were other issues related to jitter. You're probably right that it may be easiest to have it always visible.

> * The link for "Top" which appears after you scroll downwards appears in an area which is already pretty busy and this make it hard to notice. I'm wondering if it would look better in bottom right corner of the screen, as there is nothing currently there and it would be easy to spot. I get that having "top" be at the top of the page makes sense, but in its current form I think a lot of people will not notice it.

May also be viable to just remove it altogether, since it's kind of redundant with the scrollbar or keyboard navigation.

> * The popups (Profiles, Dictionaries, etc.) have headings which do not stand out enough IMO. I'm not sure if there's a better style to use here, but there should be something to make them stand out a little better.

They do kind of blend in; I wonder to what extent that might affect usability. The design is similar to the design of Chrome's settings page, and it uses this same design. A few things I can think of:
* Add an "..." to better indicate that clicking the option will open a popup/panel of some sort.
* Hover color/background change to better indicate interactivity (on devices that support hover).
* Active color/background change.

> The popups always open in full-height which can seem to be a bit overkill if there is not a lot of info to display.

The full-height ones were sized that way based on a use case where there is a lot of info in them. The two main ones which may contain "dead space" may be:
* Dictionaries - when empty, it's pretty bare, but if a user installs several dictionaries, e.g. 4-5, it fills up pretty well. Maybe the average user is only installing only one though (JMDict), so might be worth making it smaller.
* Anki card format - also pretty empty if there are very few fields; some of my testing had 10+ fields, so that's partially why I used the full size. May be worth using the smaller version.

I could have also gone the route of making the height expand based on content, but I chose not to do that for now because of how it affects button/input positions as entries are added/removed.

> * We can probably get rid of the whole About/Donate/whatever thing. There's really not really a lot that needs to be said "about" Yomichan and considering that this is a more distributed development effort at this point, having a "donation" thing there is strange too, especially considering that project has no direct monetary expenses at this point.
> 
> * ...with that being said, maybe have some sort of "Help" or "Report a bug" or something link that sends the user to GitHub?

I plan on having a general info page which shows links to the homepage, Github, version info, licenses, extension permissions, etc. So it won't be completely removed, but it will be changed to something with more info. The `?` button on the action popup will probably also direct to that.

**Comment by Thermospore** [comment]
I don't have anything particularly insightful to say, but I absolutely love the new settings page! The formatting and organization is great, and I'm glad to see more info text was added as well. Nice work, guys!

**Comment by Thermospore** [comment]
I just noticed the donations button/section is missing

also this button doesn't seem to do anything (maybe it's just unimplemented)
![image](https://user-images.githubusercontent.com/35350819/102710761-fd5dab00-4260-11eb-9469-7ca3b97ada89.png)

**Comment by toasted-nutbread** [comment]
Correct, it's unimplemented in the released version and implemented for the next release.

**Comment by PhantomAvery** [comment]
This update is really great and the new settings are very easy to navigate. I especially loved playing around with the 'Use a native browser window instead of an embedded popup' and 'Open a native browser window when copying Japanese text' options, which I hadn't noticed before. There are just a few things that I would love to see added to the advanced options pages: 
1: The option to close pop-up windows automatically once the scanning key is no longer being pressed.
- I love having this 'auto-hide' feature for instances where there is no key required to scan text. I would love to see this option added as well for situations where there is a scanning key so that the pop-up may automatically hidden after a user-inputted amount of time!
2: The ability to hide the pop-up window by pressing the scanning key on areas of websites where there is no text. 
- This feature, which I believe was present in past versions, was a huge draw for me. I loved the convenience of being able to hide the pop-up window without having to click, as it allowed me to watch subtitled content and use Yomichan without playing or pausing the video. I really loved this feature and I am finding it quite inconvenient using Yomichan with this feature not working. 
3: The option to change the text size/scale of the dictionary content when using Yomichan in a native browser window. 
- I like using Yomichan in dark mode, but this can make it difficult to read complex Kanji, so I am very happy that on this new settings page, more options have been given to change the popup scale. I would love to see customizable options like these added for the native browser window version of Yomichan as well, as I find the text a bit difficult to read. 
4: A toggle for the blue-colored text of selected dictionary entries, or the ability to change the color. 
- The blue color currently used for selected dictionary entries is quite hard to read on dark mode. I don't mind the idea, but I would love to see more options for users to control the functioning of this feature. 

Other than that, this update has been really great! Thanks for all the good work and happy holidays!

**Comment by Thermospore** [comment]
I second #⁠2! Forgot to mention it

**Comment by toasted-nutbread** [comment]
> 2: The ability to hide the pop-up window by pressing the scanning key on areas of websites where there is no text.
> 
>     * This feature, which I believe was present in past versions, was a huge draw for me. I loved the convenience of being able to hide the pop-up window without having to click, as it allowed me to watch subtitled content and use Yomichan without playing or pausing the video. I really loved this feature and I am finding it quite inconvenient using Yomichan with this feature not working.

Does this not work when the `Automatically hide results`/`Auto-hide search popup` option is enabled? That works for me, although you do have to move the cursor while holding the keys, which should have always been the case. Or am I misunderstanding the ask/what's going wrong?

**Comment by Thermospore** [comment]
Enabling that setting returns behaviour to how it was before, thanks!

I assume the behaviour of the option was changed (and the text just wasn't updated to reflect it)? I don't recall changing it

**Comment by toasted-nutbread** [comment]
> 1: The option to close pop-up windows automatically once the scanning key is no longer being pressed.
> 
>   * I love having this 'auto-hide' feature for instances where there is no key required to scan text. I would love to see this option added as well for situations where there is a scanning key so that the pop-up may automatically hidden after a user-inputted amount of time!

This is already possible, although you have to set it up using the advanced scanning options. Here is an example:
> ![image](https://user-images.githubusercontent.com/11037431/102734251-5f73ea00-430d-11eb-895c-972f40a25b83.png)

Inputs 1 and 2 are the defaults, adding a 3rd and configuring it as shown in the image will make the popup hide when Shift is not held.

**Comment by toasted-nutbread** [comment]
> 3: The option to change the text size/scale of the dictionary content when using Yomichan in a native browser window.
> 
>   * I like using Yomichan in dark mode, but this can make it difficult to read complex Kanji ...

Is this just due to the size, or something else? Is this specific to dark mode, or anything that you think could be improved?

>   * ... so I am very happy that on this new settings page, more options have been given to change the popup scale. ...

Technically the options were there on the v1 settings page, but not as well designed/organized.

> * ... I would love to see customizable options like these added for the native browser window version of Yomichan as well, as I find the text a bit difficult to read.

I can probably set up this option (or a different one) to control that as well. Native browser zoom functionality also works (CTRL++, CTRL+-, CTRL+mousewheel), although that does affect other Yomichan extension pages.


> 4: A toggle for the blue-colored text of selected dictionary entries, or the ability to change the color.
> 
>   * The blue color currently used for selected dictionary entries is quite hard to read on dark mode. I don't mind the idea, but I would love to see more options for users to control the functioning of this feature.

This was a bug and is fixed for the next patch release. The color can be adjusted by using the custom CSS option, although you would have to have some knowledge of how to edit CSS.

**Comment by PhantomAvery** [comment]
> Is this just due to the size, or something else? Is this specific to dark mode, or anything that you think could be improved?

Mostly the issue is just the size. Although I do think dark modes tend to make text more difficult to read in general, it's not something I'd fault against the program itself. Now that I'm trying the CTRL++ functions, I'm finding it works really great! Thanks very much for the help!

**Comment by FirionHope** [comment]
Bit late but wanna say that the new settings menu looks amazing, much easier to understand

**Comment by fmy1993** [comment]
![image](https://user-images.githubusercontent.com/12120788/109774305-29bb7d80-7c3b-11eb-84d5-d8a57d98a682.png)

hi,the tool is good ,but the import button is grey, I do not konw why

**Comment by toasted-nutbread** [comment]
> hi,the tool is good ,but the import button is grey, I do not konw why

Likely your Anki card settings are not configured. Use the _Configure Anki card format…_ button in the _Anki_ section to set this up.

**Comment by Aridow** [comment]
Is it possible to visually reorder the dictionaries, instead of just changing the numbers?

**Comment by toasted-nutbread** [comment]
Yes, I'm working towards supporting that; #1587. Will probably come with #1539.
